### ISSUE TITLE
recordings fail to replay.

### ISSUE THREAD

**Issue by surlyjake** [panda-re/panda#133]
Most of the recordings that i've made with qemu-x86_64 arch fail to replay and result in the following output. I could provide the recordings if needed. these were made with the codebase(@6967110e5d1c4ea980709e878ec86df93ef88839)

> 2017-01-17 14:29:13,131 INFO running panda/build/x86_64-softmmu/qemu-system-x86_64 -m 256 -replay panda_recording_debian_wheezy_i386_desktop_tut.qcow2_2017-01-17@14:28:46 -panda callstack_instr -panda stringsearch:name=foo
2017-01-17 14:29:13,155 INFO adding panda/build/x86_64-softmmu/panda/plugins/panda_callstack_instr.so to panda_plugin_files 0
2017-01-17 14:29:13,155 INFO Adding PANDA arg stringsearch:name=foo.
2017-01-17 14:29:13,155 INFO adding panda/build/x86_64-softmmu/panda/plugins/panda_stringsearch.so to panda_plugin_files 1
2017-01-17 14:29:13,155 INFO loading panda/build/x86_64-softmmu/panda/plugins/panda_callstack_instr.so
2017-01-17 14:29:13,156 INFO Initializing plugin callstack_instr
2017-01-17 14:29:13,157 INFO Success
2017-01-17 14:29:13,157 INFO loading panda/build/x86_64-softmmu/panda/plugins/panda_stringsearch.so
2017-01-17 14:29:13,157 INFO Initializing plugin stringsearch
2017-01-17 14:29:13,157 INFO panda_require: callstack_instr
2017-01-17 14:29:13,157 INFO panda_load_plugin: panda/build/x86_64-softmmu/panda/plugins/panda_callstack_instr.so already loaded
2017-01-17 14:29:13,157 INFO search strings file [foo_search_strings.txt]
2017-01-17 14:29:13,158 INFO stringsearch: added string of length 18 to search set
2017-01-17 14:29:13,158 INFO Success
2017-01-17 14:29:13,179 INFO loading snapshot
2017-01-17 14:29:13,254 INFO ... done.
2017-01-17 14:29:13,254 INFO opening nondet log for read :      ./panda_recording_debian_wheezy_i386_desktop_tut.qcow2_2017-01-17@14:28:46-rr-nondet.log
2017-01-17 14:29:14,472 INFO total_instr in replay:  776361617
2017-01-17 14:29:14,473 INFO panda_recording_debian_wheezy_i386_desktop_tut.qcow2_2017-01-17@14:28:46:     7819642 (  1.01%) instrs.    1.27 sec.  0.26 GB ram.
2017-01-17 14:29:14,599 INFO Ahead of log while looking for log entry of type RR_SKIPPED_CALL
2017-01-17 14:29:14,601 INFO {guest_instr_count=9398903 pc=0x00000000, secondary=0x00000000}
2017-01-17 14:29:14,601 INFO    RR_SKIPPED_CALL (RR_CALL_CPU_MEM_RW) from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
2017-01-17 14:29:14,601 INFO FOUND DISAGREEMENT!
2017-01-17 14:29:14,601 INFO Replay program point:
2017-01-17 14:29:14,601 INFO {guest_instr_count=9398905 pc=0x00000000, secondary=0x00000000}
2017-01-17 14:29:14,602 INFO
2017-01-17 14:29:14,602 INFO Record program point:
2017-01-17 14:29:14,602 INFO {guest_instr_count=9398903 pc=0x00000000, secondary=0x00000000}
2017-01-17 14:29:14,602 INFO
2017-01-17 14:29:14,602 INFO >>> guest instruction counts disagree
2017-01-17 14:29:14,602 INFO panda_recording_debian_wheezy_i386_desktop_tut.qcow2_2017-01-17@14:28:46:     9398905 (  1.21%) instrs.    1.40 sec.  0.26 GB ram.
2017-01-17 14:29:14,602 INFO ERROR: replay failed!
2017-01-17 14:29:14,602 INFO Time taken was: 1 seconds.
2017-01-17 14:29:14,602 INFO Stats:
2017-01-17 14:29:14,602 INFO RR_INPUT_1 number = 0, size = 0 bytes
2017-01-17 14:29:14,602 INFO RR_INPUT_2 number = 0, size = 0 bytes
2017-01-17 14:29:14,602 INFO RR_INPUT_4 number = 156, size = 4680 bytes
2017-01-17 14:29:14,603 INFO RR_INPUT_8 number = 1563, size = 53142 bytes
2017-01-17 14:29:14,603 INFO RR_INTERRUPT_REQUEST number = 461, size = 13830 bytes
2017-01-17 14:29:14,603 INFO RR_EXIT_REQUEST number = 0, size = 0 bytes
2017-01-17 14:29:14,603 INFO RR_SKIPPED_CALL number = 28, size = 2388 bytes
2017-01-17 14:29:14,603 INFO RR_DEBUG number = 0, size = 0 bytes
2017-01-17 14:29:14,603 INFO max_queue_len = 40
2017-01-17 14:29:14,603 INFO 30 items on recycle list, 3120 bytes total

**Comment by moyix** [comment]
What are you trying to record? Would it be possible to get a copy of your QCOW so we can try to reproduce?

**Comment by surlyjake** [comment]
I sourced the image from here: https://people.debian.org/~aurel32/qemu/i386/.
I'm using the wheezy desktop image.

**Comment by surlyjake** [comment]
And to answer your first question, many of the bad recordings are generated
when recording the boot process.

On Thu, Jan 19, 2017, 8:18 AM surlyjake <surlyjake@gmail.com> wrote:

I sourced the image from here: https://people.debian.org/~aurel32/qemu/i386/.
I'm using the wheezy desktop image.

On Thu, Jan 19, 2017, 6:46 AM Brendan Dolan-Gavitt <notifications@github.com>
wrote:

What are you trying to record? Would it be possible to get a copy of your
QCOW so we can try to reproduce?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/panda-re/panda/issues/133#issuecomment-273794468>, or mute
the thread

**Comment by moyix** [comment]
OK, I'll try to reproduce. Do recordings taken once the system is booted work?

**Comment by surlyjake** [comment]
it's been hard to exersise in a completely predictable manner. I have a system which is automatically starting and stopping recordings via telnet (similar to how you instrument qemu in panda-malrec) periodically. But generally speaking, the recordings that are generated of the guest while it is under load fail to replay more often than recordings of the guest while it is sitting idle.

I just tested with another image, so i booted the Fedora Cloud base image from here https://download.fedoraproject.org/pub/fedora/linux/releases/25/CloudImages/x86_64/images/Fedora-Cloud-Base-25-1.3.x86_64.qcow2

i booted and ran it, generating a new recording every ten seconds for a total of a little over 6 minutes of rutime. The first two recordings are bad, along with the 9th.

**Comment by moyix** [comment]
Ok, we can try to reproduce from that image. If you want to do some debugging on your own, I'd recommend using [Mozilla rr](https://github.com/mozilla/rr) to record the recording and then to record the replay. We have a script called [diverge.py](https://github.com/panda-re/panda/blob/master/panda/scripts/diverge.py) that can then attempt to replay the two rr recordings in lockstep and figure out where the PANDA replay diverged and why.

It doesn't always work, but you should be able to look at what it does to get an idea of how to synchronize the two states, check for differences, etc. to find out where it's going wrong.

**Comment by phulin** [comment]
This should be fixed by d643eb12a2c4ffbeeea6b51c0d560dc79438850f.

**Comment by surlyjake** [comment]
thanks, phulin. i rebuilt the new version, and it has made the failures i've seen more predictable. This is what i'm still seeing. This recording was created with ```~/panda/build/x86_64-softmmu/qemu-system-x86_64 -m 1024 -hda debian_wheezy_i386_desktop_tut.qcow2 -monitor stdio -vnc :0```

```
~/panda/build/x86_64-softmmu/qemu-system-x86_64 -m 1024 -replay giggie
loading snapshot
... done.
opening nondet log for read :	./giggie-rr-nondet.log
./giggie-rr-nondet.log:   411434127 instrs total.
giggie:     4117038 (  1.00%) instrs.    0.41 sec.  0.20 GB ram.
giggie:     8249970 (  2.01%) instrs.    0.75 sec.  0.21 GB ram.
giggie:    12347970 (  3.00%) instrs.    0.89 sec.  0.21 GB ram.
<<<....Clipped....>>>
giggie:   115205992 ( 28.00%) instrs.    4.46 sec.  0.21 GB ram.
giggie:   119345783 ( 29.01%) instrs.    4.59 sec.  0.21 GB ram.
giggie:   123451549 ( 30.01%) instrs.    4.73 sec.  0.21 GB ram.
Ahead of log while looking for log entry of type RR_SKIPPED_CALL
{guest_instr_count=125158883}
	RR_SKIPPED_CALL (RR_CALL_CPU_MEM_RW) from RR_CALLSITE_CPU_HANDLE_INTERRUPT_AFTER
FOUND DISAGREEMENT!
Replay program point:
{guest_instr_count=125158885}

Record program point:
{guest_instr_count=125158883}

>>> guest instruction counts disagree
giggie:   125158885 ( 30.42%) instrs.    4.80 sec.  0.21 GB ram.
ERROR: replay failed!
Time taken was: 5 seconds.
Stats:
RR_INPUT_1 number = 0, size = 0 bytes
RR_INPUT_2 number = 0, size = 0 bytes
RR_INPUT_4 number = 6771, size = 203130 bytes
RR_INPUT_8 number = 70592, size = 2400128 bytes
RR_INTERRUPT_REQUEST number = 13685, size = 410550 bytes
RR_EXIT_REQUEST number = 0, size = 0 bytes
RR_SKIPPED_CALL number = 35296, size = 26640044 bytes
RR_DEBUG number = 0, size = 0 bytes
max_queue_len = 233
ERROR: replay failed!
Aborted
```

i can consistently recreate this problem by running ```wget -O /dev/null http://cachefly.cachefly.net/100mb.test``` inside the recorded VM. Any recording that includes the download will fail to replay.

I'm still working to get mozzilla rr correctly capture the issue with diverge.

**Comment by phulin** [comment]
One point of recommendation - the way you're doing it should not be a problem (and we should fix whatever the issue is), but we don't usually test running 32-bit operating systems in 64-bit QEMU. I'd recommend using 32-bit QEMU instead. Many of the plugins make that assumption.

**Comment by phulin** [comment]
Unfortunately, I haven't been able to reproduce this under rr - only without. It might be that the timing change is preventing the bug from occurring.

**Comment by Dazdin9o** [comment]
I've found the same problem.It seems like that if there is some network behavior in VM,the replay will be failed.I use qemu-system-i386 to run 32-bit operating system,the commands and output are as following:
`$sudo ./debug_qemu-system-i386 -hda ../disk/disk_for_kerneldebug_i386_2_32.qcow2 -os linux-32-lava32 -replay compile_openssl -device rtl8139,vlan=0,id=net0,mac=52:54:00:32:7d:e6,bus=pci.0,addr=0x4 -net tap,script=~/timeplayer/bin_panda/scripts/qemu-ifup.sh,downscript=~/timeplayer/bin_panda/scripts/qemu-ifdown.sh`
```os_type=2 bits=32 os_details=[lava32]
loading snapshot
... done.
opening nondet log for read :   ./compile_openssl-rr-nondet.log
Ahead of log while looking for log entry of type RR_SKIPPED_CALL
{guest_instr_count=878807}
        RR_SKIPPED_CALL (RR_CALL_CPU_MEM_RW) from RR_CALLSITE_CPU_HANDLE_INTERRUPT_BEFORE
FOUND DISAGREEMENT!
Replay program point:
{guest_instr_count=878809}

Record program point:
{guest_instr_count=878807}

\>\>\> guest instruction counts disagree
compile_openssl:      878809 (  0.00%) instrs.    4.19 sec.  0.16 GB ram.
ERROR: replay failed!
Time taken was: 0 seconds.
Stats:
RR_INPUT_1 number = 0, size = 0 bytes
RR_INPUT_2 number = 0, size = 0 bytes
RR_INPUT_4 number = 397, size = 5558 bytes
RR_INPUT_8 number = 1751, size = 31518 bytes
RR_INTERRUPT_REQUEST number = 422, size = 5908 bytes
RR_EXIT_REQUEST number = 0, size = 0 bytes
RR_SKIPPED_CALL number = 532, size = 28700 bytes
max_queue_len = 193
ERROR: replay failed!
```
I login the guest(VM) by ssh,and compile the openssl while recording.

**Comment by moyix** [comment]
Does this still happen with `-net user` instead of a tap/tun device?

**Comment by Dazdin9o** [comment]
Replay successfully with `-net user`.However,you know, too many limits of guest network in user-mode networking,we even can't analysis a web server directly.It's very necessary for PADNA to support tap networking.

**Comment by phulin** [comment]
I agree in the abstract but we're still working to get replay rock-solid in the new version of QEMU. I"d suggest trying to capture your failure with https://github.com/mozilla/rr and use panda/scripts/diverge.py to find the event which is not being recorded. All you need to do is rr record the recording stage in PANDA, rr record the replay stage in QEMU, and then use panda/scripts/diverge.py on the two rr replay directories you just created (they should be in ~/.local/share/rr). It will do a binary search to find the root cause of replay divergence, and then open two gdb windows you can use to inspect further.

**Comment by Dazdin9o** [comment]
Thanks for your suggestion.
It is one possible solution.
And we will do more work, trying to solve this problem.

We will let you know when we have further results.

**Comment by Dazdin9o** [comment]
Hi,we have solved this problem by following simple patch:
```
diff --git a/main-loop.c b/main-loop.c
index 4d4ccfd..af39fed 100644
--- a/main-loop.c
+++ b/main-loop.c
@@ -523,7 +523,9 @@ int main_loop_wait(int nonblocking)
     // ru: add check if in in replay for running timers
     if (!rr_in_replay()) {
         qemu_start_warp_timer();
+        rr_begin_main_loop_wait();
         qemu_clock_run_all_timers();
+        rr_end_main_loop_wait();
     }

     return ret;

```
It's really a bug,would you accept this patch?

**Comment by phulin** [comment]
That patch looks good. Feel free to submit a pull request.
